// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-bqtVB9OJWySSnBT1vAl3foVfFrzmZCU',
    appId: '1:231437816796:web:4ce685506e2f309b2a3519',
    messagingSenderId: '231437816796',
    projectId: 'event-management-app-ae56f',
    authDomain: 'event-management-app-ae56f.firebaseapp.com',
    storageBucket: 'event-management-app-ae56f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcIPwwgyOE3ZxJN09WJe5Z_jfeGzZSsYc',
    appId: '1:231437816796:android:7d600346985515c02a3519',
    messagingSenderId: '231437816796',
    projectId: 'event-management-app-ae56f',
    storageBucket: 'event-management-app-ae56f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsrzCP1y0yHePmljMomTA7_SDXe43mgZ8',
    appId: '1:231437816796:ios:5f8e30fded4cc15c2a3519',
    messagingSenderId: '231437816796',
    projectId: 'event-management-app-ae56f',
    storageBucket: 'event-management-app-ae56f.appspot.com',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsrzCP1y0yHePmljMomTA7_SDXe43mgZ8',
    appId: '1:231437816796:ios:5f8e30fded4cc15c2a3519',
    messagingSenderId: '231437816796',
    projectId: 'event-management-app-ae56f',
    storageBucket: 'event-management-app-ae56f.appspot.com',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-bqtVB9OJWySSnBT1vAl3foVfFrzmZCU',
    appId: '1:231437816796:web:8518a677c0feeb4a2a3519',
    messagingSenderId: '231437816796',
    projectId: 'event-management-app-ae56f',
    authDomain: 'event-management-app-ae56f.firebaseapp.com',
    storageBucket: 'event-management-app-ae56f.appspot.com',
  );

}